### ISSUE TITLE
Library can not parse older formatted WSDL files

### ISSUE THREAD

**Issue by MehmetCagriK** [elixir-soap/soap#110]
In the function Soap.Wsdl.get_soap_namespace, the function searches for one of these URLs
```
  @soap_version_namespaces %{
    "1.1" => :"http://schemas.xmlsoap.org/wsdl/soap/",
    "1.2" => :"http://schemas.xmlsoap.org/wsdl/soap12/"
  }
```
However, older WSDL files do not have any of these lines since there were only one SOAP format back then. An example is: https://schemas.xmlsoap.org/ws/2005/04/discovery/ws-discovery.wsdl

This error, in return, causes program to give timeout error:
```
** (HTTPoison.Error) :timeout
    (httpoison 1.8.2) lib/httpoison.ex:258: HTTPoison.request!/5
    (soap 1.1.0) lib/soap/wsdl.ex:23: Soap.Wsdl.parse_from_url/2
    iex:3: (file)
```
If I hack get_soap_namespace function to return 'soap' value as hardcoded return value, things work well, wsdl is parsed correctly.

**Comment by VitorTrin** [comment]
This seems to be soap 1.0. The lib states that the minimum supported version is 1.1.
